In [1]:
import numpy as np

In [ ]:
A = np.array([
    [3, 5], 
    [2, 7]])
B = np.array([[1, 9], 
              [6, 0]])
print(A.shape, B.shape)

(2, 2) (2, 2)


In [3]:
A + B

array([[ 4, 14],
       [ 8,  7]])

In [4]:
A - B

array([[ 2, -4],
       [-4,  7]])

In [ ]:
"""
C = np.array([
    [3, 45], 
    [12, 0]])
"""
A * B 

array([[ 3, 45],
       [12,  0]])

In [6]:
A @ B

array([[33, 27],
       [44, 18]])

In [7]:
np.matmul(A, B)

array([[33, 27],
       [44, 18]])

In [8]:
A + 5

array([[ 8, 10],
       [ 7, 12]])

In [9]:
B - 10

array([[ -9,  -1],
       [ -4, -10]])

---
# Random

In [14]:
np.random.random()

0.5945308852330047

In [36]:
C = np.random.randint(256, size=(1920, 1080), dtype=np.uint8)
D = np.random.randint(256, size=(1920, 1080), dtype=np.uint8)

In [37]:
C + D

array([[206, 110, 127, ...,  93,  94, 223],
       [130, 107, 117, ..., 131, 223,   0],
       [223, 174, 144, ..., 108, 151,  52],
       ...,
       [ 27, 148, 187, ..., 217,  75,  18],
       [116,  36, 222, ..., 110,  73, 229],
       [ 38,  45, 239, ..., 196, 210, 173]],
      shape=(1920, 1080), dtype=uint8)

In [38]:
D - C

array([[ 44,  40, 127, ...,  15,   2, 153],
       [ 22, 233, 137, ..., 205, 117,  42],
       [175,  46,  48, ..., 144,  25, 210],
       ...,
       [ 45, 156,  11, ..., 199,  61,  90],
       [ 16,  12, 100, ...,  46,  17,  47],
       [ 98,  63, 179, ...,  76, 110,   5]],
      shape=(1920, 1080), dtype=uint8)

In [39]:
C * D

array([[141,  65, 128, ..., 186, 160,  52],
       [  8, 170,  10, ...,  56,  50,  71],
       [168, 128,   0, ...,  36, 168, 147],
       ...,
       [188, 160, 136, ...,  80, 220, 104],
       [228,  32,  93, ..., 192, 108,  14],
       [  8,  26, 254, ..., 224,  64, 180]],
      shape=(1920, 1080), dtype=uint8)

In [41]:
E = np.random.randint(256, size=(2000, 2000), dtype=np.uint8)
F = np.random.randint(256, size=(2000, 2000), dtype=np.uint8)

In [42]:
E @ F

array([[ 20,  33,  93, ..., 115,  90,  19],
       [ 73, 175,  31, ..., 153, 131,   4],
       [168, 244, 152, ...,  67, 154,   6],
       ...,
       [100,  82,  69, ..., 143,   9, 149],
       [176, 132,  94, ..., 137, 174, 233],
       [238,  31, 175, ...,  33, 208,  48]],
      shape=(2000, 2000), dtype=uint8)

In [43]:
np.random.seed(27)

In [45]:
np.random.randint(10, size=(10, 10))

array([[3, 6, 1, 4, 1, 8, 1, 2, 4, 2],
       [0, 4, 5, 9, 6, 0, 7, 3, 4, 5],
       [3, 0, 0, 4, 5, 8, 2, 2, 9, 0],
       [4, 7, 9, 3, 5, 3, 9, 0, 1, 7],
       [8, 7, 6, 6, 5, 9, 9, 4, 4, 1],
       [4, 8, 9, 4, 4, 1, 2, 6, 2, 2],
       [3, 3, 1, 7, 0, 4, 6, 9, 9, 9],
       [3, 8, 9, 9, 2, 7, 1, 4, 9, 5],
       [2, 4, 3, 5, 7, 2, 4, 9, 4, 8],
       [0, 9, 7, 0, 5, 5, 9, 3, 5, 1]])

In [47]:
mat1 = np.random.randint(10, size=(5, 6))
mat1.shape

(5, 6)

In [49]:
mat1.T.shape

(6, 5)

In [50]:
mat1

array([[9, 4, 0, 6, 8, 3],
       [1, 1, 9, 0, 5, 9],
       [2, 0, 7, 6, 1, 6],
       [5, 9, 3, 1, 0, 1],
       [5, 1, 0, 5, 1, 2]])

In [ ]:
for i in range(7):
    for j in range(5):
        print(mat1[i, j])

9
4
0
6
8
1
1
9
0
5
2
0
7
6
1
5
9
3
1
0
5
1
0
5
1


IndexError: index 5 is out of bounds for axis 0 with size 5