In [1]:
import numpy as np

In [2]:
A = np.array([
    [3, 5], 
    [2, 7]])
B = np.array([[1, 9], 
              [6, 0]])
print(A.shape, B.shape)

(2, 2) (2, 2)


In [3]:
A + B

array([[ 4, 14],
       [ 8,  7]])

In [4]:
A - B

array([[ 2, -4],
       [-4,  7]])

In [5]:
"""
C = np.array([
    [3, 45], 
    [12, 0]])
"""
A * B 

array([[ 3, 45],
       [12,  0]])

In [6]:
A @ B

array([[33, 27],
       [44, 18]])

In [7]:
np.matmul(A, B)

array([[33, 27],
       [44, 18]])

In [8]:
A + 5

array([[ 8, 10],
       [ 7, 12]])

In [9]:
B - 10

array([[ -9,  -1],
       [ -4, -10]])

---
# Random

In [10]:
np.random.random()

0.7123713289212252

In [11]:
C = np.random.randint(256, size=(1920, 1080), dtype=np.uint8)
D = np.random.randint(256, size=(1920, 1080), dtype=np.uint8)

In [12]:
C + D

array([[ 39, 183,  32, ...,  33,  99, 249],
       [ 86, 114, 145, ...,  53, 153, 157],
       [130,  16, 172, ...,  59, 246,  71],
       ...,
       [250, 170, 119, ..., 172,  28,  13],
       [184,  60,  57, ...,  18,  43,  95],
       [ 25, 128, 173, ..., 208, 173, 111]],
      shape=(1920, 1080), dtype=uint8)

In [13]:
D - C

array([[ 25, 211, 106, ..., 135, 231, 141],
       [108,  48,  79, ...,  57, 163,  71],
       [242,  40, 208, ...,  97, 132,  69],
       ...,
       [244, 212,  11, ...,  92, 142, 165],
       [ 74,  28,   3, ..., 148,  97, 231],
       [ 91, 254,  21, ..., 232, 249, 255]],
      shape=(1920, 1080), dtype=uint8)

In [14]:
C * D

array([[224, 186,   7, ..., 196, 246,  34],
       [213, 113, 112, ..., 146, 234, 166],
       [ 80, 176, 164, ...,  54,  21, 198],
       ...,
       [229,  85, 182, ..., 160,  19,  20],
       [183, 192, 170, ..., 237, 158,  52],
       [134, 255, 204, ..., 176,  46,   8]],
      shape=(1920, 1080), dtype=uint8)

In [15]:
E = np.random.randint(256, size=(2000, 2000), dtype=np.uint8)
F = np.random.randint(256, size=(2000, 2000), dtype=np.uint8)

In [16]:
E @ F

array([[239, 110,  29, ...,   0, 167, 224],
       [ 97, 209, 124, ..., 191, 185, 115],
       [242, 122, 230, ..., 152,  50,  20],
       ...,
       [ 70, 182, 185, ..., 108, 113,  68],
       [108, 142, 243, ...,  23,  24,  65],
       [215,  53,  31, ...,  44, 108, 120]],
      shape=(2000, 2000), dtype=uint8)

In [17]:
np.random.seed(27)

In [18]:
np.random.randint(10, size=(10, 10))

array([[3, 8, 8, 8, 0, 5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3, 3, 0, 5, 3, 3],
       [6, 7, 2, 7, 8, 5, 7, 1, 2, 0],
       [3, 3, 5, 3, 5, 0, 7, 7, 4, 1],
       [1, 7, 0, 7, 8, 4, 9, 0, 4, 7],
       [0, 9, 2, 2, 3, 0, 1, 5, 9, 5],
       [1, 3, 9, 6, 5, 7, 3, 4, 4, 4],
       [2, 0, 2, 4, 9, 8, 0, 7, 5, 6],
       [2, 2, 0, 0, 3, 5, 6, 3, 7, 6],
       [7, 3, 2, 2, 3, 7, 0, 2, 2, 6]])

In [33]:
mat1 = np.random.randint(10, size=(200, 200))
mat1.shape

(200, 200)

In [20]:
mat1.T.shape

(6, 5)

In [21]:
mat1

array([[3, 6, 1, 4, 1, 8],
       [1, 2, 4, 2, 0, 4],
       [5, 9, 6, 0, 7, 3],
       [4, 5, 3, 0, 0, 4],
       [5, 8, 2, 2, 9, 0]])

In [34]:
fila, columna = mat1.shape

In [35]:
print(fila, columna)

200 200


In [26]:
len(mat1)

5

In [36]:
for i in range(fila): # Filas
    for j in range(columna): # Columnas
        print(mat1[i, j])

4
7
9
3
5
3
9
0
1
7
8
7
6
6
5
9
9
4
4
1
4
8
9
4
4
1
2
6
2
2
3
3
1
7
0
4
6
9
9
9
3
8
9
9
2
7
1
4
9
5
2
4
3
5
7
2
4
9
4
8
0
9
7
0
5
5
9
3
5
1
1
6
1
9
6
1
4
2
9
6
7
7
0
5
1
0
3
8
6
9
0
8
8
4
5
4
0
4
0
3
9
4
0
6
8
3
1
1
9
0
5
9
2
0
7
6
1
6
5
9
3
1
0
1
5
1
0
5
1
2
8
1
9
0
5
1
8
6
5
0
8
7
1
2
9
7
8
2
4
7
1
5
1
9
1
7
5
7
7
9
3
8
1
9
9
8
7
9
6
0
2
0
4
7
1
4
7
3
5
6
6
7
1
1
9
8
8
1
6
2
8
9
7
2
2
4
7
5
9
9
5
9
2
7
0
8
6
6
2
2
6
9
4
6
1
1
0
4
5
2
7
4
1
5
1
6
8
2
7
9
6
9
0
9
2
3
0
2
6
3
4
2
8
0
1
0
5
7
4
5
3
6
7
6
8
7
8
5
1
3
6
0
5
5
4
9
1
2
2
0
8
0
6
0
1
2
0
7
8
1
5
3
4
6
9
4
5
5
7
6
2
5
4
0
8
0
4
7
1
4
2
7
5
9
1
3
6
2
0
1
7
9
2
7
6
3
2
2
6
9
9
3
4
3
3
4
6
7
7
0
2
1
1
2
2
5
8
2
8
7
6
2
2
0
8
3
0
7
6
1
2
0
4
8
6
6
7
3
7
3
3
8
3
2
3
7
4
6
5
8
8
6
3
4
2
2
7
0
5
6
6
0
9
6
4
8
3
5
0
6
7
7
5
1
6
9
4
7
9
6
0
0
9
2
0
4
1
3
2
0
0
1
3
5
0
6
4
5
9
1
3
8
5
3
3
0
0
3
8
4
5
1
1
4
0
7
7
7
0
0
9
4
8
6
0
8
6
7
5
9
9
6
2
4
6
3
6
4
0
9
6
3
8
8
7
1
2
3
2
4
7
1
5
2
0
2
6
2
2
0
8
8
3
7
2
0
9
0
8
7
8
0
4
5
5
8
2
4
7
9


In [38]:
# Visite todos los elementos de una matriz 200x200 y a c/u de los elementos le sume 10
mat2 = np.random.randint(10, size=(200, 200))
print(mat2)

fila, columna = mat2.shape

for i in range(fila): # Filas
    for j in range(columna): # Columnas
        mat2[i, j] += 10

mat2

[[4 9 3 ... 8 1 7]
 [9 8 8 ... 4 0 0]
 [7 6 7 ... 5 7 3]
 ...
 [8 1 5 ... 8 6 2]
 [5 5 9 ... 7 7 5]
 [3 8 0 ... 0 8 1]]


array([[14, 19, 13, ..., 18, 11, 17],
       [19, 18, 18, ..., 14, 10, 10],
       [17, 16, 17, ..., 15, 17, 13],
       ...,
       [18, 11, 15, ..., 18, 16, 12],
       [15, 15, 19, ..., 17, 17, 15],
       [13, 18, 10, ..., 10, 18, 11]], shape=(200, 200))

In [39]:
mat2 + 10

array([[24, 29, 23, ..., 28, 21, 27],
       [29, 28, 28, ..., 24, 20, 20],
       [27, 26, 27, ..., 25, 27, 23],
       ...,
       [28, 21, 25, ..., 28, 26, 22],
       [25, 25, 29, ..., 27, 27, 25],
       [23, 28, 20, ..., 20, 28, 21]], shape=(200, 200))

# Copia de ndarrays

In [40]:
type(mat2)

numpy.ndarray

In [ ]:
# así NO se hace una copia
mat3 = mat2 

In [42]:
type(mat3)

numpy.ndarray

In [43]:
mat3

array([[14, 19, 13, ..., 18, 11, 17],
       [19, 18, 18, ..., 14, 10, 10],
       [17, 16, 17, ..., 15, 17, 13],
       ...,
       [18, 11, 15, ..., 18, 16, 12],
       [15, 15, 19, ..., 17, 17, 15],
       [13, 18, 10, ..., 10, 18, 11]], shape=(200, 200))

In [44]:
mat3[0,0] = 100

In [45]:
mat3

array([[100,  19,  13, ...,  18,  11,  17],
       [ 19,  18,  18, ...,  14,  10,  10],
       [ 17,  16,  17, ...,  15,  17,  13],
       ...,
       [ 18,  11,  15, ...,  18,  16,  12],
       [ 15,  15,  19, ...,  17,  17,  15],
       [ 13,  18,  10, ...,  10,  18,  11]], shape=(200, 200))

In [46]:
mat2

array([[100,  19,  13, ...,  18,  11,  17],
       [ 19,  18,  18, ...,  14,  10,  10],
       [ 17,  16,  17, ...,  15,  17,  13],
       ...,
       [ 18,  11,  15, ...,  18,  16,  12],
       [ 15,  15,  19, ...,  17,  17,  15],
       [ 13,  18,  10, ...,  10,  18,  11]], shape=(200, 200))

Así SÍ se hace una copia de arreglos

In [ ]:
mat4 = mat2.copy() # deep copy

In [48]:
type(mat4)

numpy.ndarray

In [49]:
mat4

array([[100,  19,  13, ...,  18,  11,  17],
       [ 19,  18,  18, ...,  14,  10,  10],
       [ 17,  16,  17, ...,  15,  17,  13],
       ...,
       [ 18,  11,  15, ...,  18,  16,  12],
       [ 15,  15,  19, ...,  17,  17,  15],
       [ 13,  18,  10, ...,  10,  18,  11]], shape=(200, 200))

In [50]:
mat2[0, 0] = 500

In [52]:
mat2

array([[500,  19,  13, ...,  18,  11,  17],
       [ 19,  18,  18, ...,  14,  10,  10],
       [ 17,  16,  17, ...,  15,  17,  13],
       ...,
       [ 18,  11,  15, ...,  18,  16,  12],
       [ 15,  15,  19, ...,  17,  17,  15],
       [ 13,  18,  10, ...,  10,  18,  11]], shape=(200, 200))

In [51]:
mat4

array([[100,  19,  13, ...,  18,  11,  17],
       [ 19,  18,  18, ...,  14,  10,  10],
       [ 17,  16,  17, ...,  15,  17,  13],
       ...,
       [ 18,  11,  15, ...,  18,  16,  12],
       [ 15,  15,  19, ...,  17,  17,  15],
       [ 13,  18,  10, ...,  10,  18,  11]], shape=(200, 200))

---

In [61]:
A = np.random.randint(256, size=(1920, 1080), dtype=np.uint8)
B = np.random.randint(256, size=(1920, 1080), dtype=np.uint8).T

In [68]:
A = A.astype(np.float32)
B = B.astype(np.float32)

In [63]:
print(A.shape, B.shape)

(1920, 1080) (1080, 1920)


In [64]:
A

array([[191., 205., 185., ...,  43., 174.,  87.],
       [158., 139.,  39., ..., 137., 159.,  51.],
       [ 62.,  29., 161., ...,  78.,  47.,  26.],
       ...,
       [248., 211., 189., ..., 224.,  97., 221.],
       [ 86.,  59.,  90., ..., 236., 153., 181.],
       [197.,  40.,  20., ...,  55., 154., 123.]], shape=(1920, 1080))

In [69]:
A @ B

array([[1.7309112e+07, 1.7565530e+07, 1.7618662e+07, ..., 1.7394088e+07,
        1.7569664e+07, 1.7647270e+07],
       [1.8116336e+07, 1.8241918e+07, 1.8773602e+07, ..., 1.8451528e+07,
        1.8555032e+07, 1.8518864e+07],
       [1.7431342e+07, 1.7544840e+07, 1.7551428e+07, ..., 1.7316750e+07,
        1.7850882e+07, 1.8260990e+07],
       ...,
       [1.7898332e+07, 1.7898930e+07, 1.8253894e+07, ..., 1.7822632e+07,
        1.7537036e+07, 1.8194896e+07],
       [1.8069312e+07, 1.7963034e+07, 1.8437138e+07, ..., 1.8129344e+07,
        1.8394440e+07, 1.8426598e+07],
       [1.6872104e+07, 1.7203118e+07, 1.7763388e+07, ..., 1.7040448e+07,
        1.7544236e+07, 1.7292114e+07]], shape=(1920, 1920), dtype=float32)